version: '3.3'
services:
  site_devfolify:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: site-devfolify
    restart: unless-stopped
    ports:
      - 9987:3000